# This is a sample build configuration for Haskell.
# Check our guides at https://confluence.atlassian.com/x/VYk8Lw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: haskell:latest

pipelines:
  default:
    - step:
        script: # Modify the commands below to build your repository.
          - apt-get update && apt-get install -y xz-utils make libghc-gtk-dev gtk+3.0-dev
          - stack setup --upgrade-cabal
          - stack install gtk2hs-buildtools
          - stack test
